apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: lmwprac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: sonarqube
          image: sonarqube:latest
          env:
            - name: SONAR_SEARCH_JAVAADDITIONALOPTS
              value: "-Xms512m -Xmx512m"
            - name: SONAR_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-secret
                  key: SONAR_JDBC_URL
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-secret
                  key: SONAR_JDBC_USERNAME
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-secret
                  key: SONAR_JDBC_PASSWORD
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data
            - mountPath: /opt/sonarqube/extensions
              name: sonarqube-extensions
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-lmw-pvc
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions-lmw-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: lmwprac
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer  # Change to NodePort if needed
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-lmw-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/sonarqube/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions-lmw-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/sonarqube/extensions"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-lmw-pvc
  namespace: lmwprac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-lmw-pvc
  namespace: lmwprac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual