apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: lmwprac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          env:
            - name: SONAR_SEARCH_JAVAADDITIONALOPTS
              value: "-Xms512m -Xmx512m"
            - name: SONAR_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-secret
                  key: SONAR_JDBC_URL
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-secret
                  key: SONAR_JDBC_USERNAME
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-secret
                  key: SONAR_JDBC_PASSWORD
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: lmwprac
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer  # Change to NodePort if needed