apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: el-eventlistener
  namespace: lmwprac
spec:
  triggers:
    - name: trigger
      bindings:
        - ref: trigger-binding
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ["pull_request", "push", "repository"]
      template:
        ref: trigger-template

