apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: lmwprac
spec:
  params:
  - name: github-clone-url
    type: string
    description: The URL of the GitHub repository to clone
  steps:
  - name: git-clone
    image: alpine/git
    script: |
      #!/bin/sh
      git clone $(inputs.params.github-clone-url) $(workspaces.source.path)
      cd $(workspaces.source.path)
      echo "Repository cloned to $(workspaces.source.path)"
  workspaces:
  - name: git-credentials
  - name: source
