apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-deploy
spec:
  params:
    - name: MANIFEST_PATH
      type: string
      description: Path to the manifest to apply
    - name: YAML_PATH_TO_IMAGE 
      type: string
      description: The path to the image to replace in the yaml manifest (arg to yq)
    - name: IMAGE 
      type: string
      description: The name of the image that was built 
    - name: ACTION
      type: string
      description: The action to perform with kubectl
  steps:
    - name: replace-image
      image: mikefarah/yq
      workingDir: $(workspaces.source.path)
      script: |
        yq -i  '$(params.YAML_PATH_TO_IMAGE) = "$(params.IMAGE)"' $(params.MANIFEST_PATH)
    - name: run-kubectl 
      image: lachlanevenson/k8s-kubectl
      workingDir: $(workspaces.source.path)
      script: |
        kubectl $(params.ACTION) -f $(params.MANIFEST_PATH)
  workspaces:
    - name: source
  results:
    - name: IMAGE 
      description: The name of the image that was built