apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sonarqube-scan
  namespace: lmwprac
spec:
  params:
    - name: SONAR_HOST_URL
      type: string
      description: "SonarQube server URL"
    - name: PROJECT_KEY
      type: string
      description: "Project key in SonarQube"
  steps:
    - name: run-sonarqube
      image: sonarsource/sonar-scanner-cli:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonar-token  
              key: SONAR_TOKEN 
      script: |
        #!/bin/sh
        set -e
        echo "Sonar token (masked for security): ${SONAR_TOKEN:0:4}******"
        cd $(workspaces.source.path)
        sonar-scanner \
          -Dsonar.projectKey=$(params.PROJECT_KEY) \
          -Dsonar.sources=. \
          -Dsonar.host.url=$(params.SONAR_HOST_URL) \
          -Dsonar.token=$SONAR_TOKEN
  workspaces:
  - name: source 