apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-run
  namespace: lmwprac
spec:
  params:
  - name: KUBENETES_DIR
    type: string
    description: Directory containing Kubernetes manifest files
  steps:
  - name: kubectl-apply
    image: lachlanevenson/k8s-kubectl
    workingDir: $(workspaces.source.path)
    script: |
      # Apply all Kubernetes manifests in the specified directory
      kubectl apply -f $(params.KUBENETES_DIR)
  workspaces:
  - name: source