apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/healthcheck-path: "/live"
  name: ingress-trigger
  namespace: lmwprac
spec:
  ingressClassName: nginx
  rules:
    # - host: trigger.lmwprac.dev.clusters.easlab.co.uk
    # - host: trigger.lmwprac.lmw.clusters.easlab.co.uk
    - host: trigger.lmwprac.hyades.clusters.easlab.co.uk
      http:
        paths:
          - backend:
              service:
                name: el-eventlistener
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        # - trigger.lmwprac.dev.clusters.easlab.co.uk
        # - trigger.lmwprac.lmw.clusters.easlab.co.uk
        - trigger.lmwprac.hyades.clusters.easlab.co.uk
      secretName: trigger-lmwprac-tls
