apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
  namespace: lmwprac
spec:
  params:
  - name: github-clone-url
    description: The GitHub repository URL to clone
  - name: IMAGE
    description: The image reference to push to the registry
  - name: DOCKERFILE
    description: The path to the Dockerfile to build
  - name: CONTEXT
    description: The build context used by Kaniko.
  - name: MANIFEST_PATH
    description: The Kubernetes manifest file
  - name: YAML_PATH_TO_IMAGE
    description: The path to the image field in the manifest
  - name: ACTION
    description: The action to perform with kubectl
  - name: KUBENETES_DIR
    description: The directory to apply the manifest
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: clone-build-push-pipeline-run-
      namespace: lmwprac
    spec:
      pipelineRef:
        name: clone-build-push-pipeline
      params:
      - name: github-clone-url
        value: $(tt.params.github-clone-url)
      - name: IMAGE
        value: $(tt.params.IMAGE)
      - name: DOCKERFILE
        value: $(tt.params.DOCKERFILE)
      - name: CONTEXT
        value: $(tt.params.CONTEXT)
      - name: MANIFEST_PATH
        value: $(tt.params.MANIFEST_PATH)
      - name: YAML_PATH_TO_IMAGE
        value: $(tt.params.YAML_PATH_TO_IMAGE)
      - name: ACTION
        value: $(tt.params.ACTION)
      - name: KUBENETES_DIR
        value: $(tt.params.KUBENETES_DIR)
      workspaces:
        - name: source
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: git-credentials
          secret:
            secretName: git-credentials
        - name: docker-config
          secret:
            secretName: docker-config
