apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec:
  params:
    - name: github-clone-url
      value: $(body.repository.clone_url)
    - name: IMAGE
      value: index.docker.io/lmwcode/$(body.repository.name):$(body.head_commit.id)
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: "."
    - name: KUBERNETES_MANIFEST_PATH
      value: "k8s/deployment.yaml"
    - name: HELM_MANIFEST_PATH
      value: "helm_webapp/templates/deployment.yaml"
    - name: YAML_PATH_TO_IMAGE
      value: ".spec.template.spec.containers[0].image"
    - name: ACTION
      value: apply
    # - name: KUBENETES_DIR
    #   value: "k8s"
    - name: RELEASE_NAME
      value: $(body.repository.name)
    - name: CHART_DIR
      value: helm_webapp
    - name: NAMESPACE
      value: lmwprac