apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec:
  params:
    - name: github-clone-url
      value: $(body.repository.clone_url)
    - name: IMAGE
      value: index.docker.io/lmwcode/$(body.repository.name):V.1.0.0
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: "."
    - name: MANIFEST_PATH
      value: "k8s/deployment.yaml"
    - name: YAML_PATH_TO_IMAGE
      value: ".spec.template.spec.containers[0].image"
    - name: ACTION
      value: apply