apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push-pipeline
  namespace: lmwprac
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry   
  params:
    - name: GITHUB_CLONE_URL
      type: string
      description: "The URL of the Git repository"
    - name: SONAR_HOST_URL
      type: string
      description: "SonarQube server URL"
    - name: PROJECT_KEY
      type: string
      description: "Project key in SonarQube"
    - name: IMAGE
      type: string
      description: "The container registry where the image will be pushed"
    - name: DOCKERFILE
      type: string
      description: "Path to the Dockerfile to build. Defaults to ./Dockerfile"
    - name: CONTEXT
      type: string
      description: "The build context used by Kaniko. Defaults to /workspace/source"
    - name: EXTRA_ARGS
      type: string
      description: "Additional arguments to pass to Kaniko. Defaults to --cache=true"
    - name: BUILDER_IMAGE
      type: string
      description: "The image to use as the builder. Defaults to gcr.io/kaniko-project/executor:latest"
    - name: TRIVY_SEVERITY
      type: string
      description: "Comma-separated list of severities to scan for. Defaults to CRITICAL,HIGH"
    - name: HELM_MANIFEST_PATH
      type: string
      description: "Path to the Helm manifest file"
    - name: YAML_PATH_TO_IMAGE
      type: string
      description: "Path to the image field in the manifest"
    - name: RELEASE_NAME
      type: string
      description: "The name of the Helm release"
    - name: CHART_DIR
      type: string
      description: "Directory containing the Helm chart"
    - name: NAMESPACE
      type: string
      description: "Kubernetes namespace for the release"
  workspaces:
    - name: git-credentials
    - name: source
    - name: docker-config
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: GITHUB_CLONE_URL
          value: $(params.GITHUB_CLONE_URL)
      workspaces:
        - name: git-credentials
          workspace: git-credentials
        - name: source
          workspace: source

    - name: sonarqube-scan
      runAfter: ["git-clone"]
      taskRef:
        name: sonarqube-scan
        kind: Task
      params:
        - name: SONAR_HOST_URL
          value: $(params.SONAR_HOST_URL)
        - name: PROJECT_KEY
          value: $(params.PROJECT_KEY)
      workspaces:
        - name: source
          workspace: source

    - name: kaniko-docker-build
      runAfter: ["sonarqube-scan"]
      taskRef:
        name: kaniko-docker-build
        kind: Task
      workspaces:
      - name: source
        workspace: source
      - name: docker-config
        workspace: docker-config
      params:
      - name: IMAGE
        value: $(params.IMAGE)
      - name: DOCKERFILE
        value: $(params.DOCKERFILE)
      - name: CONTEXT
        value: $(params.CONTEXT)
      - name: EXTRA_ARGS
        value: $(params.EXTRA_ARGS)
      - name: BUILDER_IMAGE
        value: $(params.BUILDER_IMAGE)

    - name: trivy-scan
      runAfter: ["kaniko-docker-build"]
      taskRef:
        name: trivy-scan
        kind: Task
      params:
      - name: TRIVY_SEVERITY
        value: $(params.TRIVY_SEVERITY)
      - name: IMAGE
        value: $(params.IMAGE)

    - name: go-test
      runAfter: ["kaniko-docker-build"]
      taskRef:
        name: go-test
        kind: Task
      workspaces:
        - name: source
          workspace: source
      
    - name: update-docker-image
      runAfter: 
        - trivy-scan
        - go-test
      taskRef:
        name: update-docker-image
        kind: Task
      params:
        - name: HELM_MANIFEST_PATH
          value: $(params.HELM_MANIFEST_PATH)
        - name: YAML_PATH_TO_IMAGE
          value: $(params.YAML_PATH_TO_IMAGE)
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: source 

    - name: helm-deploy
      runAfter: ["update-docker-image"]
      taskRef:
        name: helm-deploy
        kind: Task
      params:
        - name: RELEASE_NAME
          value: $(params.RELEASE_NAME)
        - name: CHART_DIR
          value: $(params.CHART_DIR)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
      workspaces:
        - name: source
          workspace: source