apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-docker-image
  namespace: lmwprac
spec:
  params:
    - name: HELM_MANIFEST_PATH
      type: string
      description: Path to the helm manifest to change image name
    - name: YAML_PATH_TO_IMAGE 
      type: string
      description: The path to the image to replace in the yaml manifest (arg to yq)
    - name: IMAGE 
      type: string
      description: The name of the image that was built 
  steps:
    - name: update-docker-image
      image: mikefarah/yq
      workingDir: $(workspaces.source.path)
      script: |
        yq -i '$(params.YAML_PATH_TO_IMAGE) = "$(params.IMAGE)"' $(params.HELM_MANIFEST_PATH)
  workspaces:
    - name: source
  results:
    - name: IMAGE 
      description: The name of the image that was built