apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2025-02-25T11:24:35Z"
  name: git-credentials
  namespace: lmwprac
  resourceVersion: "176452766"
  uid: 3102a717-b48e-47a6-beff-e58dc005daba
type: Opaque
data:
  .git-credentials: aHR0cHM6Ly9sYXVyYXdhcnJlbjg4OmdocF9YM2FvZzhBMGR6QTg3QTBYdTRJM0V0ODNsMHZhRUcyNVNzUkFAZ2l0aHViLmNvbQo=
  .gitconfig: W3VzZXJdCiAgICBuYW1lID0gbGF1cmF3YXJyZW44OAogICAgZW1haWwgPSBsYXVyYUBlbnRlcnByaXNlYXV0b21hdGlvbi5jby51awo=